name: devops-2-3

services:

  frontend:
      build: 
        context: ./frontend
        dockerfile: ./frontend.Dockerfile
      ports:
        - "5000:5000"
      container_name: frontend-2-3

  backend:
    build:
      context: ./backend
      dockerfile: ./backend.Dockerfile
    ports:
      - "8080:8080"
    container_name: backend-2-3